### ISSUE TITLE
What is the font name in screenshots/illustrations in README ?

### ISSUE THREAD

**Issue by Sakyce** [cognate-lang/cognate#21]
It looks cool and very sexy.
![image](https://user-images.githubusercontent.com/55030860/212702177-de501698-f403-4c71-82cb-81ac122d3b32.png)

But what is the font name ? Would be cool if you credit it.

**Comment by StavromulaBeta** [comment]
The font is called Hermit (https://pcaro.es/hermit/)

:)

**Comment by StavromulaBeta** [comment]
sure, I think I can add it as mouseover text to the screenshots

**Comment by StavromulaBeta** [comment]
done!
